// AUTO-GENERATED from the clinic price list by scripts/generate-catalog.ps1.
// Do not edit by hand. Price = "other doctors" column; durationMin is a
// placeholder (60 min, Lumecca 30). specialistIds are NOT set here -- each
// provider attaches them (mock: own ids, Cliniccards: real doctor_id).

import type { Category } from "@/domain/types";

/** Catalog service without specialistIds (a provider attaches them). */
export interface CatalogService {
  id: string;
  name: string;
  categoryId: string;
  durationMin: number;
  price: number;
}

export const CATALOG_CATEGORIES: Category[] = [
  { id: "cat-0", name: "Консультації Дерматологічні", order: 0 },
  { id: "cat-1", name: "Фотоомолодження обличчя Lumecca", order: 1 },
  { id: "cat-2", name: "Лікування Акне, Постакне, Рубці, Розацеа", order: 2 },
  { id: "cat-3", name: "Пілінги", order: 3 },
  { id: "cat-4", name: "Мезотерапія", order: 4 },
  { id: "cat-5", name: "Ботулінотерапія ЖІНКИ", order: 5 },
  { id: "cat-7", name: "Лазерне шліфування ResurFX", order: 6 },
  { id: "cat-8", name: "Чистки", order: 7 },
  { id: "cat-9", name: "Масажі", order: 8 },
  { id: "cat-10", name: "Апарат Eve Ace of Face", order: 9 },
  { id: "cat-11", name: "Ботулінотерапія ЧОЛОВІКИ", order: 10 },
  { id: "cat-12", name: "Гіпергідроз ЖІНКИ", order: 11 },
  { id: "cat-13", name: "Гіпергідроз ЧОЛОВІКИ", order: 12 },
  { id: "cat-14", name: "Лікування мігрені препаратом Диспорт", order: 13 },
  { id: "cat-15", name: "Біоревіталізація", order: 14 },
  { id: "cat-16", name: "Контурна пластика губ", order: 15 },
  { id: "cat-18", name: "Розчинення філера", order: 16 },
  { id: "cat-19", name: "Контурна пластика Підборіддя, Скул", order: 17 },
  { id: "cat-21", name: "Колагеностимулюючі препарати", order: 18 },
  { id: "cat-22", name: "Заповнення заломів / бланшинг", order: 19 },
  { id: "cat-23", name: "Стимуляція росту волосся", order: 20 },
  { id: "cat-24", name: "Фотоомолодження тіла Lumecca", order: 21 },
  { id: "cat-25", name: "Morpheus8 обличчя", order: 22 },
  { id: "cat-26", name: "Morpheus8 тіло", order: 23 },
  { id: "cat-27", name: "Ліполітики", order: 24 },
  { id: "cat-29", name: "Видалення новоутворень (радіоніж)", order: 25 },
];

export const CATALOG_SERVICES: CatalogService[] = [
  { id: "svc-0", name: "Консультація дерматологічна", categoryId: "cat-0", durationMin: 60, price: 1500 },
  { id: "svc-1", name: "Консультація трихологічна", categoryId: "cat-0", durationMin: 60, price: 1500 },
  { id: "svc-2", name: "Консультація трихологічна+ дерматологічна", categoryId: "cat-0", durationMin: 60, price: 2000 },
  { id: "svc-3", name: "Повторна консультація", categoryId: "cat-0", durationMin: 60, price: 800 },
  { id: "svc-4", name: "Консультація косметологічна (Підбір догляду, індивідуальний план процедур)", categoryId: "cat-0", durationMin: 60, price: 800 },
  { id: "svc-5", name: "Дерматоскопія родимок або інших новоутворень", categoryId: "cat-0", durationMin: 60, price: 1350 },
  { id: "svc-6", name: "Діагностика шкіри апаратом Puremi", categoryId: "cat-0", durationMin: 60, price: 1000 },
  { id: "svc-7", name: "Пакет консультацій системне лікування (на весь період лікування) старший лікар", categoryId: "cat-0", durationMin: 60, price: 8000 },
  { id: "svc-8", name: "IPL Lumecca обличчя повністю", categoryId: "cat-1", durationMin: 30, price: 3700 },
  { id: "svc-9", name: "IPL Lumecca зона лоба", categoryId: "cat-1", durationMin: 30, price: 2300 },
  { id: "svc-10", name: "IPL Lumecca верхня губа", categoryId: "cat-1", durationMin: 30, price: 2000 },
  { id: "svc-11", name: "IPL Lumecca носа", categoryId: "cat-1", durationMin: 30, price: 2400 },
  { id: "svc-12", name: "IPL Lumecca крила носа", categoryId: "cat-1", durationMin: 30, price: 2000 },
  { id: "svc-13", name: "IPL Lumecca зона щок", categoryId: "cat-1", durationMin: 30, price: 2600 },
  { id: "svc-14", name: "IPL Lumecca 1см2", categoryId: "cat-1", durationMin: 30, price: 800 },
  { id: "svc-15", name: "Пілінг обличчя Acne Peel", categoryId: "cat-2", durationMin: 60, price: 2500 },
  { id: "svc-16", name: "Пілінг обличчя Green Peel", categoryId: "cat-2", durationMin: 60, price: 2500 },
  { id: "svc-17", name: "Пілінг обличчя Jessner Peel", categoryId: "cat-2", durationMin: 60, price: 2950 },
  { id: "svc-18", name: "Ін'єкції Дипроспану у зону обличчя", categoryId: "cat-2", durationMin: 60, price: 2500 },
  { id: "svc-19", name: "Ін'єкції  Дипроспану у зону спини", categoryId: "cat-2", durationMin: 60, price: 2500 },
  { id: "svc-20", name: "Ін'єкції Флостерону у зону обличчя", categoryId: "cat-2", durationMin: 60, price: 2500 },
  { id: "svc-21", name: "Ін'єкції Флостерону у зону спини", categoryId: "cat-2", durationMin: 60, price: 2500 },
  { id: "svc-22", name: "Азелаїново-саліциловий пілінг ОБЛИЧЧЯ Simildiet", categoryId: "cat-3", durationMin: 60, price: 1500 },
  { id: "svc-23", name: "Азелаїново-саліциловий пілінг ОБЛИЧЧЯ та ШИЇ Simildiet", categoryId: "cat-3", durationMin: 60, price: 2200 },
  { id: "svc-24", name: "Азелаїново-саліциловий пілінг СПИНИ Simildiet", categoryId: "cat-3", durationMin: 60, price: 3000 },
  { id: "svc-25", name: "Пілінг СПИНИ Acne Peel", categoryId: "cat-3", durationMin: 60, price: 4500 },
  { id: "svc-26", name: "Заспокійлива зволожуюча маска для обличчя", categoryId: "cat-3", durationMin: 60, price: 600 },
  { id: "svc-27", name: "Пілінг ОБЛИЧЧЯ BioRePeel", categoryId: "cat-3", durationMin: 60, price: 2400 },
  { id: "svc-28", name: "Пілінг ДЕКОЛЬТЕ BioRePeel", categoryId: "cat-3", durationMin: 60, price: 2200 },
  { id: "svc-29", name: "Пілінг ОБЛИЧЧЯ та ДЕКОЛЬТЕ BioRePeel", categoryId: "cat-3", durationMin: 60, price: 3800 },
  { id: "svc-30", name: "Пілінг ОБЛИЧЧЯ , ШИЯ та ДЕКОЛЬТЕ BioRePeel", categoryId: "cat-3", durationMin: 60, price: 5000 },
  { id: "svc-31", name: "Ферментотерапія ОБЛИЧЧЯ та ШИЇ DMK Dane", categoryId: "cat-3", durationMin: 60, price: 3500 },
  { id: "svc-32", name: "Ферментотерапія ОБЛИЧЧЯ, ШИЇ та ДЕКОЛЬТЕ DMK Dane", categoryId: "cat-3", durationMin: 60, price: 4000 },
  { id: "svc-33", name: "Пілінг обличчя Quck peel", categoryId: "cat-3", durationMin: 60, price: 1900 },
  { id: "svc-34", name: "Ретиноловий пілінг обличчя Lighening", categoryId: "cat-3", durationMin: 60, price: 2300 },
  { id: "svc-35", name: "Пілінг ОБЛИЧЧЯ APPeex (ТСА 20%, ПДРН 5%, В12)", categoryId: "cat-3", durationMin: 60, price: 2500 },
  { id: "svc-36", name: "Пілінг ШИЇ APPeex (ТСА 20%, ПДРН 5%, В12)", categoryId: "cat-3", durationMin: 60, price: 1400 },
  { id: "svc-37", name: "Пілінг ДЕКОЛЬТЕ APPeex (ТСА 20%, ПДРН 5%, В12)", categoryId: "cat-3", durationMin: 60, price: 1900 },
  { id: "svc-38", name: "Пілінг Обличчя Appeex strong (TCA 35%, ПДРН 5%, В12)", categoryId: "cat-3", durationMin: 60, price: 2800 },
  { id: "svc-39", name: "Пілінг обличчя PRX-T33", categoryId: "cat-3", durationMin: 60, price: 2400 },
  { id: "svc-40", name: "Пілінг обличчя Salicylic 20% gel peel image", categoryId: "cat-3", durationMin: 60, price: 1500 },
  { id: "svc-41", name: "Пілінг Glycolic 50% gel peel image", categoryId: "cat-3", durationMin: 60, price: 1500 },
  { id: "svc-42", name: "Молочний пілінг Medic8", categoryId: "cat-3", durationMin: 60, price: 2000 },
  { id: "svc-43", name: "Revive mask Заспокійлива маска з нідосомами", categoryId: "cat-4", durationMin: 60, price: 600 },
  { id: "svc-44", name: "Полінуклеотиди TwAc eyes(1ml) (очі)", categoryId: "cat-4", durationMin: 60, price: 4500 },
  { id: "svc-45", name: "Полінуклеотиди TwAc 2.0 (3ml)", categoryId: "cat-4", durationMin: 60, price: 7000 },
  { id: "svc-46", name: "Полінуклеотиди TwAc 3.0 (3ml)", categoryId: "cat-4", durationMin: 60, price: 7300 },
  { id: "svc-47", name: "Нідосоми Revive NX", categoryId: "cat-4", durationMin: 60, price: 9000 },
  { id: "svc-48", name: "Курс 3 процедури Нідосоми Revive NX", categoryId: "cat-4", durationMin: 60, price: 20950 },
  { id: "svc-49", name: "Полінуклеотиди Rejuran S", categoryId: "cat-4", durationMin: 60, price: 5000 },
  { id: "svc-50", name: "Полінуклеотиди Rejuran I (очі)", categoryId: "cat-4", durationMin: 60, price: 5000 },
  { id: "svc-51", name: "Полінуклеотиди Rejuran HB (1ml)", categoryId: "cat-4", durationMin: 60, price: 5000 },
  { id: "svc-52", name: "Полінуклеотиди Rejuran healer (2ml)", categoryId: "cat-4", durationMin: 60, price: 7000 },
  { id: "svc-53", name: "Полінуклеотиди Vitaran I (1ml)", categoryId: "cat-4", durationMin: 60, price: 5000 },
  { id: "svc-54", name: "Полінуклеотиди Vitaran II (2ml)", categoryId: "cat-4", durationMin: 60, price: 7000 },
  { id: "svc-55", name: "Полінуклеотиди Tox eye Face Collagen Vitaran(2ml) (обличчя, шия)", categoryId: "cat-4", durationMin: 60, price: 7000 },
  { id: "svc-56", name: "Полінуклеотиди Whitening & Anti-Age Vitaran(2ml)", categoryId: "cat-4", durationMin: 60, price: 7000 },
  { id: "svc-57", name: "Канюля", categoryId: "cat-4", durationMin: 60, price: 200 },
  { id: "svc-58", name: "Ботулінотерапія препаратом Dysport ЧОЛО+МІЖБРІВ'Я ЖІНОЧИЙ", categoryId: "cat-5", durationMin: 60, price: 6200 },
  { id: "svc-59", name: "Ботулінотерапія препаратом Dysport зони ЧОЛА ЖІНОЧИЙ", categoryId: "cat-5", durationMin: 60, price: 3400 },
  { id: "svc-60", name: "Ботулінотерапія препаратом Dysport зони МІЖБРІВ'Я ЖІНОЧИЙ", categoryId: "cat-5", durationMin: 60, price: 3400 },
  { id: "svc-61", name: "Ботулінотерапія препаратом Dysport зони «ГУСЯЧІ ЛАПКИ» ЖІНОЧИЙ", categoryId: "cat-5", durationMin: 60, price: 3400 },
  { id: "svc-62", name: "Ботулінотерапія препаратом Dysport зони НОСА ЖІНОЧИЙ", categoryId: "cat-5", durationMin: 60, price: 2200 },
  { id: "svc-63", name: "Ботулінотерапія препаратом Dysport зони ГІНГІВАЛЬНОЇ ПОСМІШКИ ЖІНОЧИЙ", categoryId: "cat-5", durationMin: 60, price: 2200 },
  { id: "svc-64", name: "Ботулінотерапія препаратом Dysport зони КИСЕТНИХ ЗМОРШОК ЖІНОЧИЙ", categoryId: "cat-5", durationMin: 60, price: 2200 },
  { id: "svc-65", name: "Ботулінотерапія препаратом Dysport зони ПІДБОРІДДЯ ЖІНОЧИЙ", categoryId: "cat-5", durationMin: 60, price: 2400 },
  { id: "svc-66", name: "Ботулінотерапія препаратом Dysport зони МАССЕТЕР ЖІНОЧИЙ", categoryId: "cat-5", durationMin: 60, price: 6000 },
  { id: "svc-67", name: "Ботулінотерапія препаратом Dysport зони ПЛАТІЗМА ЖІНОЧИЙ", categoryId: "cat-5", durationMin: 60, price: 7500 },
  { id: "svc-68", name: "Ботулінотерапія препаратом Dysport підняття кінчика носа ЖІНОЧИЙ", categoryId: "cat-5", durationMin: 60, price: 2200 },
  { id: "svc-69", name: "Бейбі ботох", categoryId: "cat-5", durationMin: 60, price: 10000 },
  { id: "svc-70", name: "Full face", categoryId: "cat-5", durationMin: 60, price: 15600 },
  { id: "svc-71", name: "Шліфування обличчя ResurFX", categoryId: "cat-7", durationMin: 60, price: 6000 },
  { id: "svc-72", name: "Лазерне шліфування зони щік ResurFX", categoryId: "cat-7", durationMin: 60, price: 4000 },
  { id: "svc-73", name: "Лазерне шліфування зони шиї ResurFX", categoryId: "cat-7", durationMin: 60, price: 4000 },
  { id: "svc-74", name: "Лазерне шліфування зони декольте ResurFX", categoryId: "cat-7", durationMin: 60, price: 5000 },
  { id: "svc-75", name: "Лазерне шліфування зони обличчя, шия, декольте ResurFX", categoryId: "cat-7", durationMin: 60, price: 13000 },
  { id: "svc-76", name: "Лазерна блефаропластика ResurFX", categoryId: "cat-7", durationMin: 60, price: 3000 },
  { id: "svc-77", name: "Лазерне шліфування кистей рук ResurFX", categoryId: "cat-7", durationMin: 60, price: 3700 },
  { id: "svc-78", name: "Стрії розмір долоні", categoryId: "cat-7", durationMin: 60, price: 2500 },
  { id: "svc-79", name: "Лазерне шліфування зони обличчя 1см кв.", categoryId: "cat-7", durationMin: 60, price: 700 },
  { id: "svc-80", name: "Лазерне шліфування зони тіла 1см кв.", categoryId: "cat-7", durationMin: 60, price: 700 },
  { id: "svc-81", name: "3д омолодження шкіри обличчя (термоліфтинг обличчя IPL Lumecca + лазерний душ обличчя ResurFX + пілінг обличчя Appeex peel)", categoryId: "cat-7", durationMin: 30, price: 8000 },
  { id: "svc-82", name: "Лазерне шліфування зони спини повністю", categoryId: "cat-7", durationMin: 60, price: 13000 },
  { id: "svc-83", name: "Чистка гідропілінг (гідрофлінг з алмазним пілінгом, чистка+ маска по проблематиці шкіри)", categoryId: "cat-8", durationMin: 60, price: 3200 },
  { id: "svc-84", name: "Комбінована чистка обличчя + азелоїново-саліциловий пілінг обличчя", categoryId: "cat-8", durationMin: 60, price: 2000 },
  { id: "svc-85", name: "Комбінована чистка спини + азелоїново-саліциловий пілінг спини", categoryId: "cat-8", durationMin: 60, price: 3500 },
  { id: "svc-86", name: "Комбінована чистка спини", categoryId: "cat-8", durationMin: 60, price: 2500 },
  { id: "svc-87", name: "Комбінована чистка обличчя + пілінг обличчя APPeex", categoryId: "cat-8", durationMin: 60, price: 3200 },
  { id: "svc-88", name: "Комбінована чистка обличчя + пілінг обличчя BioRePeel", categoryId: "cat-8", durationMin: 60, price: 3200 },
  { id: "svc-89", name: "Комбінована чистка обличчя Clear Choice", categoryId: "cat-8", durationMin: 60, price: 3000 },
  { id: "svc-90", name: "Комбінована чистка обличчя + пілінг обличчя Quick Peel", categoryId: "cat-8", durationMin: 60, price: 2700 },
  { id: "svc-91", name: "Комбінована чистка обличчя + фотоомолодження обличчя IPL Lumecca + пілінг обличчя BioRePeel", categoryId: "cat-8", durationMin: 30, price: 6000 },
  { id: "svc-92", name: "Комбінована чистка обличчя + фотоомолодження обличчя IPL Lumecca + пілінг обличчя APPeex", categoryId: "cat-8", durationMin: 30, price: 7000 },
  { id: "svc-93", name: "Комбінована чистка обличчя + ферментотерапія обличчя 1 маска", categoryId: "cat-8", durationMin: 60, price: 3900 },
  { id: "svc-94", name: "Комбінована чистка обличчя + ферментотерапія обличчя повний протокол", categoryId: "cat-8", durationMin: 60, price: 5000 },
  { id: "svc-95", name: "Комбінована чистка спини + Пілінг Acne Peel", categoryId: "cat-8", durationMin: 60, price: 5400 },
  { id: "svc-96", name: "Складність 2", categoryId: "cat-8", durationMin: 60, price: 600 },
  { id: "svc-97", name: "Складність 3", categoryId: "cat-8", durationMin: 60, price: 1200 },
  { id: "svc-98", name: "Масаж обличчя та зони декольте + лімфодренаж 30хв", categoryId: "cat-9", durationMin: 60, price: 1300 },
  { id: "svc-99", name: "Масаж обличчя та зони декольте + лімфодренаж 60хв", categoryId: "cat-9", durationMin: 60, price: 2000 },
  { id: "svc-100", name: "Масаж обличчя та зони декольте + лімфодренаж 90хв", categoryId: "cat-9", durationMin: 60, price: 2600 },
  { id: "svc-101", name: "Масаж обличчя  для проблемної шкіри(гідропілінг+масаж), зони декольте  + лімфодренаж", categoryId: "cat-9", durationMin: 60, price: 57000 },
  { id: "svc-102", name: "Гідропілінг на апараті EVE Ace of Face", categoryId: "cat-10", durationMin: 60, price: 1600 },
  { id: "svc-103", name: "Мікротоки на апараті Eve Ace of Face", categoryId: "cat-10", durationMin: 60, price: 1400 },
  { id: "svc-104", name: "Елктро міостимуляція EVE Ace of Face", categoryId: "cat-10", durationMin: 60, price: 1400 },
  { id: "svc-105", name: "Супер комплекс (гідропілінг+ масаж+ мікротоки/EMS на вибір)", categoryId: "cat-10", durationMin: 60, price: 3700 },
  { id: "svc-106", name: "Комплекс на ліфтинг (Масаж+ мікротоки/EMS на вибір)", categoryId: "cat-10", durationMin: 60, price: 2500 },
  { id: "svc-107", name: "Супер комбо апаратні (гідропілінг з алмазним пілінгом+ мікротоки+ EMS)", categoryId: "cat-10", durationMin: 60, price: 3700 },
  { id: "svc-108", name: "Ботулінотерапія препаратом Dysport зони ЧОЛА ЧОЛОВІЧИЙ", categoryId: "cat-11", durationMin: 60, price: 4000 },
  { id: "svc-109", name: "Ботулінотерапія препаратом Dysport зони МІЖБРІВ'Я ЧОЛОВІЧИЙ", categoryId: "cat-11", durationMin: 60, price: 4000 },
  { id: "svc-110", name: "Ботулінотерапія препаратом Dysport  ЧОЛА+МІЖБРІВ'Я  ЧОЛОВІЧИЙ", categoryId: "cat-11", durationMin: 60, price: 7300 },
  { id: "svc-111", name: "Ботулінотерапія препаратом Dysport «ГУСЯЧІ ЛАПКИ» ЧОЛОВІЧИЙ", categoryId: "cat-11", durationMin: 60, price: 3900 },
  { id: "svc-112", name: "Ботулінотерапія препаратом Dysport НОСА ЧОЛОВІЧИЙ", categoryId: "cat-11", durationMin: 60, price: 2600 },
  { id: "svc-113", name: "Ботулінотерапія препаратом Dysport ГІНГІВАЛЬНОЇ ПОСМІШКИ ЧОЛОВІЧИЙ", categoryId: "cat-11", durationMin: 60, price: 2600 },
  { id: "svc-114", name: "Ботулінотерапія препаратом Dysport КИСЕТНИХ ЗМОРШОК ЧОЛОВІЧИЙ", categoryId: "cat-11", durationMin: 60, price: 2600 },
  { id: "svc-115", name: "Ботулінотерапія препаратом Dysport ПІДБОРІДДЯ ЧОЛОВІЧИЙ", categoryId: "cat-11", durationMin: 60, price: 3000 },
  { id: "svc-116", name: "Ботулінотерапія препаратом Dysport МАССЕТЕР  ЧОЛОВІЧИЙ", categoryId: "cat-11", durationMin: 60, price: 7300 },
  { id: "svc-117", name: "Ботулінотерапія препаратом Dysport ПЛАТІЗМА  ЧОЛОВІЧИЙ", categoryId: "cat-11", durationMin: 60, price: 9600 },
  { id: "svc-118", name: "Ботулінотерапія препаратом Dysport підняття кінчика носа ЧОЛОВІЧИЙ", categoryId: "cat-11", durationMin: 60, price: 2500 },
  { id: "svc-119", name: "Лікування Гіпергідрозу ПАХВ препаратом Dysport ЖІНОЧИЙ", categoryId: "cat-12", durationMin: 60, price: 10500 },
  { id: "svc-120", name: "Лікування Гіпергідрозу СТУПНЕЙ препаратом Dysport ЖІНОЧИЙ", categoryId: "cat-12", durationMin: 60, price: 10500 },
  { id: "svc-121", name: "Лікування Гіпергідрозу ДОЛОНЕЙ препаратом Dysport ЖІНОЧИЙ", categoryId: "cat-12", durationMin: 60, price: 10500 },
  { id: "svc-122", name: "Лікування Гіпергідрозу ПАХВ препаратом Neuranox ЖІНОЧИЙ", categoryId: "cat-12", durationMin: 60, price: 9000 },
  { id: "svc-123", name: "Лікування Гіпергідрозу СТУПНЕЙ препаратом Neuranox ЖІНОЧИЙ", categoryId: "cat-12", durationMin: 60, price: 9000 },
  { id: "svc-124", name: "Лікування Гіпергідрозу ДОЛОНЕЙ препаратом Neuranox ЖІНОЧИЙ", categoryId: "cat-12", durationMin: 60, price: 9000 },
  { id: "svc-125", name: "Лікування Гіпергідрозу ПАХВ препаратом Dysport ЧОЛОВІЧИЙ", categoryId: "cat-13", durationMin: 60, price: 13000 },
  { id: "svc-126", name: "Лікування Гіпергідрозу СТУПНЕЙ препаратом Dysport ЧОЛОВІЧИЙ", categoryId: "cat-13", durationMin: 60, price: 13000 },
  { id: "svc-127", name: "Лікування Гіпергідрозу ДОЛОНЕЙ препаратом Dysport ЧОЛОВІЧИЙ", categoryId: "cat-13", durationMin: 60, price: 13000 },
  { id: "svc-128", name: "Лікування Гіпергідрозу ПАХВ препаратом Neuranox ЧОЛОВІЧИЙ", categoryId: "cat-13", durationMin: 60, price: 11500 },
  { id: "svc-129", name: "Лікування Гіпергідрозу СТУПНЕЙ препаратом Neuranox ЧОЛОВІЧИЙ", categoryId: "cat-13", durationMin: 60, price: 11500 },
  { id: "svc-130", name: "Лікування Гіпергідрозу ДОЛОНЕЙ препаратом Neuranox ЧОЛОВІЧИЙ", categoryId: "cat-13", durationMin: 60, price: 11500 },
  { id: "svc-131", name: "Лікування мігрені препаратом Диспорт", categoryId: "cat-14", durationMin: 60, price: 13000 },
  { id: "svc-132", name: "Teosyal PureSens Redencity 1", categoryId: "cat-15", durationMin: 60, price: 9000 },
  { id: "svc-133", name: "Інєкції амінокислоти у зону обличчя Jalupro HMW 3ml", categoryId: "cat-15", durationMin: 60, price: 6500 },
  { id: "svc-134", name: "Інєкції амінокислоти у зону обличчя Jalupro classic 6ml", categoryId: "cat-15", durationMin: 60, price: 7100 },
  { id: "svc-135", name: "Інєкції амінокислоти у зону обличчяJalupro classic 3ml", categoryId: "cat-15", durationMin: 60, price: 4000 },
  { id: "svc-136", name: "Інєкції амінокислоти у зону очей препаратом Jalupro Young Eye 1мл", categoryId: "cat-15", durationMin: 60, price: 7000 },
  { id: "svc-137", name: "Інєкції амінокислоти у зону обличчя препаратом Jalupro Super Hydro 2.5мл", categoryId: "cat-15", durationMin: 60, price: 8500 },
  { id: "svc-138", name: "Аугеметація губ препаратом Phillex fine lips (1,1 ml)", categoryId: "cat-16", durationMin: 60, price: 7500 },
  { id: "svc-139", name: "Аугеметація губ препаратом Phillex deep plus(1,1 ml)", categoryId: "cat-16", durationMin: 60, price: 7800 },
  { id: "svc-140", name: "Аугеметація губ препаратом Teosyal RHA kiss(0,7ml)", categoryId: "cat-16", durationMin: 60, price: 8000 },
  { id: "svc-141", name: "Аугеметація губ препаратом Teosyal RHA 2(1ml)", categoryId: "cat-16", durationMin: 60, price: 8500 },
  { id: "svc-142", name: "Аугеметація губ препаратом Teosyal RHA 3(1ml)", categoryId: "cat-16", durationMin: 60, price: 9000 },
  { id: "svc-143", name: "Аугеметація губ препаратом Teosyal kiss(1ml)", categoryId: "cat-16", durationMin: 60, price: 9500 },
  { id: "svc-144", name: "Аугеметація губ препаратом Louna (1.1ml)", categoryId: "cat-16", durationMin: 60, price: 7500 },
  { id: "svc-145", name: "Розчинення філера в губах препаратом PB Serum", categoryId: "cat-18", durationMin: 60, price: 2500 },
  { id: "svc-146", name: "Контурна пластика ПІДБОРІДДЯ препаратом Phillex sab- Q(1,1ml)", categoryId: "cat-19", durationMin: 60, price: 8000 },
  { id: "svc-147", name: "Контурна пластика СКУЛ препаратом Phillex sab- Q(1,1ml)", categoryId: "cat-19", durationMin: 60, price: 8000 },
  { id: "svc-148", name: "Контурна пластика Скул+підборіддя 2 мл", categoryId: "cat-19", durationMin: 60, price: 14000 },
  { id: "svc-149", name: "Контурна пластика Скул+підборіддя 3 мл", categoryId: "cat-19", durationMin: 60, price: 20000 },
  { id: "svc-150", name: "Контурна пластика ПІДБОРІДДЯ препаратом Teosyal 4 (1ml)", categoryId: "cat-19", durationMin: 60, price: 9500 },
  { id: "svc-151", name: "Контурна пластика СКУЛ препаратом Teosyal 4 (1ml)", categoryId: "cat-19", durationMin: 60, price: 9500 },
  { id: "svc-152", name: "Контурна пластика ПІДБОРІДДЯ препаратом Teosyal puresense ultra deep(1,2ml)", categoryId: "cat-19", durationMin: 60, price: 9700 },
  { id: "svc-153", name: "Колагеностимуляція зони ОБЛИЧЧЯ препаратом Rediesse", categoryId: "cat-21", durationMin: 60, price: 13000 },
  { id: "svc-154", name: "Колагеностимуляція зони ШИЇ препаратом Rediesse", categoryId: "cat-21", durationMin: 60, price: 13000 },
  { id: "svc-155", name: "Колагеностимуляція зони ОБЛИЧЧЯ препаратом Rediesse 2 шприці", categoryId: "cat-21", durationMin: 60, price: 23000 },
  { id: "svc-156", name: "Колагеностимуляція зони ОБЛИЧЧЯ препаратом Karisma", categoryId: "cat-21", durationMin: 60, price: 9000 },
  { id: "svc-157", name: "Колагеностимуляція зони ШИЇ препаратом Karisma", categoryId: "cat-21", durationMin: 60, price: 9000 },
  { id: "svc-158", name: "Ін'єкції полімолочної кислоти Juve Look у зону ОЧЕЙ", categoryId: "cat-21", durationMin: 60, price: 8500 },
  { id: "svc-159", name: "Ін'єкції полімолочної кислоти Juve Look у зону ШИЇ", categoryId: "cat-21", durationMin: 60, price: 10000 },
  { id: "svc-160", name: "Ін'єкції полімолочної кислоти Juve Look у зону ОБЛИЧЧЯ", categoryId: "cat-21", durationMin: 60, price: 11000 },
  { id: "svc-161", name: "Ін'єкції полімолочної кислоти Juve Look у зону ДЕКОЛЬТЕ", categoryId: "cat-21", durationMin: 60, price: 11000 },
  { id: "svc-162", name: "Ін'єкції полімолочної кислоти Juve Look у зону ОБЛИЧЧЯ та ДЕКОЛЬТЕ", categoryId: "cat-21", durationMin: 60, price: 16500 },
  { id: "svc-163", name: "Ін'єкції полімолочної кислоти Juve Look у зону ОБЛИЧЧЯ та ОЧІ", categoryId: "cat-21", durationMin: 60, price: 14300 },
  { id: "svc-164", name: "Ін'єкції полімолочної кислоти Juve Look у зону ОБЛИЧЧЯ та ШИЇ", categoryId: "cat-21", durationMin: 60, price: 16500 },
  { id: "svc-165", name: "Ін'єкції полімолочної кислоти Juve Look у зону ОБЛИЧЧЯ, ШИЯ та ОЧІ", categoryId: "cat-21", durationMin: 60, price: 19800 },
  { id: "svc-166", name: "Lenisna 1фл", categoryId: "cat-21", durationMin: 60, price: 16000 },
  { id: "svc-167", name: "ZQ-II полі L-молочна кислота 1шп", categoryId: "cat-21", durationMin: 60, price: 13000 },
  { id: "svc-168", name: "Заповнення зморшок в зоні ОБЛИЧЧЯ препаратом на основі гіалуронової кислоти Belotero soft (1мл)", categoryId: "cat-22", durationMin: 60, price: 8000 },
  { id: "svc-169", name: "Заповнення зморшок в зоні ШИЇ препаратом на основі гіалуронової кислоти Belotero soft (1мл)", categoryId: "cat-22", durationMin: 60, price: 8000 },
  { id: "svc-170", name: "Заповнення зморшок навколо зони ОЧЕЙ препаратом на основі гіалуронової кислоти Belotero soft (1мл)", categoryId: "cat-22", durationMin: 60, price: 8000 },
  { id: "svc-171", name: "Заповнення зморшок в зоні ОБЛИЧЧЯ препаратом на основі гіалуронової кислоти Belotero balance (1мл)", categoryId: "cat-22", durationMin: 60, price: 8500 },
  { id: "svc-172", name: "Заповнення зморшок в зоні ШИЇ препаратом на основі гіалуронової кислоти Belotero balance (1мл)", categoryId: "cat-22", durationMin: 60, price: 8500 },
  { id: "svc-173", name: "Заповнення заломів з зоні НОСОСЛІЗНОЇ борозди препаратом Teosyal Redensity 2", categoryId: "cat-22", durationMin: 60, price: 9000 },
  { id: "svc-174", name: "Лікування андрогенетичної алопеції препаратом DUTABIOT", categoryId: "cat-23", durationMin: 60, price: 4300 },
  { id: "svc-175", name: "Стимуляція росту волосся голови препаратом Biocascad", categoryId: "cat-23", durationMin: 60, price: 4500 },
  { id: "svc-176", name: "Плазмотерапія шкіри голови 1 пробірка", categoryId: "cat-23", durationMin: 60, price: 3200 },
  { id: "svc-177", name: "Плазмотерапія шкіри голови 2 пробірки", categoryId: "cat-23", durationMin: 60, price: 3900 },
  { id: "svc-178", name: "Плазмотерапія шкіри голови 4 пробірки", categoryId: "cat-23", durationMin: 60, price: 5300 },
  { id: "svc-179", name: "IPL Lumecca шия", categoryId: "cat-24", durationMin: 30, price: 2600 },
  { id: "svc-180", name: "IPL Lumecca декольте", categoryId: "cat-24", durationMin: 30, price: 3000 },
  { id: "svc-181", name: "IPL Lumecca обличчя та шия", categoryId: "cat-24", durationMin: 30, price: 5400 },
  { id: "svc-182", name: "Фотоомолодження зони ОБЛИЧЧЯ, ШИЇ та ДЕКОЛЬТЕ IPL Lumecca", categoryId: "cat-24", durationMin: 30, price: 6500 },
  { id: "svc-183", name: "Фотоомолодження зони плечей IPL Lumecca", categoryId: "cat-24", durationMin: 30, price: 4000 },
  { id: "svc-184", name: "Фотоомолодження спини IPL Lumecca", categoryId: "cat-24", durationMin: 30, price: 5500 },
  { id: "svc-185", name: "Фотоомолодження спини та плечей IPL Lumecca", categoryId: "cat-24", durationMin: 30, price: 75000 },
  { id: "svc-186", name: "Фотоомолодження зони грудей IPL Lumecca", categoryId: "cat-24", durationMin: 30, price: 4000 },
  { id: "svc-187", name: "Фотоомолодження кистей рук IPL Lumecca", categoryId: "cat-24", durationMin: 30, price: 3000 },
  { id: "svc-188", name: "Фотоомолодження зони рук до ліктя IPL Lumecca", categoryId: "cat-24", durationMin: 30, price: 4500 },
  { id: "svc-189", name: "Фотоомолодження рук повністю IPL Lumecca", categoryId: "cat-24", durationMin: 30, price: 5500 },
  { id: "svc-190", name: "Фотоомолодження 1см2 тіла IPL Lumecca", categoryId: "cat-24", durationMin: 30, price: 800 },
  { id: "svc-191", name: "Мікроголковий RF ліфтинг обличчя Morpheus8", categoryId: "cat-25", durationMin: 60, price: 14000 },
  { id: "svc-192", name: "Мікроголковий RF ліфтинг зони очей, щок та підборіддя Morpheus8", categoryId: "cat-25", durationMin: 60, price: 10500 },
  { id: "svc-193", name: "Мікроголковий RF ліфтинг зони декольте Morpheus8", categoryId: "cat-25", durationMin: 60, price: 11600 },
  { id: "svc-194", name: "Мікроголковий RF ліфтинг зони шиї Morpheus8", categoryId: "cat-25", durationMin: 60, price: 11600 },
  { id: "svc-195", name: "Мікроголковий RF ліфтинг зони обличчя та шиї Morpheus8", categoryId: "cat-25", durationMin: 60, price: 17600 },
  { id: "svc-196", name: "Мікроголковий RF ліфтинг зони обличчя, шиї та декольте Morpheus8", categoryId: "cat-25", durationMin: 60, price: 19800 },
  { id: "svc-197", name: "Екзосоми", categoryId: "cat-25", durationMin: 60, price: 7500 },
  { id: "svc-198", name: "Мікроголковий RF ліфтинг зони ГРУДЕЙ Morpheus8", categoryId: "cat-26", durationMin: 60, price: 16500 },
  { id: "svc-199", name: "Мікроголковий RF ліфтинг зони ЖИВОТА Morpheus8", categoryId: "cat-26", durationMin: 60, price: 16500 },
  { id: "svc-200", name: "Мікроголковий RF ліфтинг БОКОВОЇ ЗОНИ ТАЛІЇ Morpheus8", categoryId: "cat-26", durationMin: 60, price: 16500 },
  { id: "svc-201", name: "Мікроголковий RF ліфтинг зони КОЛІН Morpheus8", categoryId: "cat-26", durationMin: 60, price: 16500 },
  { id: "svc-202", name: "Мікроголковий RF ліфтинг зони РУК ДО ЛІКТЯ Morpheus8", categoryId: "cat-26", durationMin: 60, price: 16500 },
  { id: "svc-203", name: "Мікроголковий RF ліфтинг зони ВЕРХНЯ ТРЕТИНА Morpheus8", categoryId: "cat-26", durationMin: 60, price: 16500 },
  { id: "svc-204", name: "Мікроголковий RF ліфтинг зони НИЖНЯ ТРЕТИНА Morpheus8", categoryId: "cat-26", durationMin: 60, price: 16500 },
  { id: "svc-205", name: "Мікроголковий RF ліфтинг зони ВНУТРІШНЬОЇ ПОВЕРХНі СТЕГНА Morpheus8", categoryId: "cat-26", durationMin: 60, price: 16500 },
  { id: "svc-206", name: "Мікроголковий RF ліфтинг зони ЗОВНІШНЬОЇ ПОВЕРХНі СТЕГНА Morpheus8", categoryId: "cat-26", durationMin: 60, price: 16500 },
  { id: "svc-207", name: "Мікроголковий RF ліфтинг зони СІДНИЦЬ Morpheus8", categoryId: "cat-26", durationMin: 60, price: 16500 },
  { id: "svc-208", name: "Мікроголковий RF ліфтинг тіла Morpheus8 2 зони на вибір", categoryId: "cat-26", durationMin: 60, price: 27500 },
  { id: "svc-209", name: "Ін'єкція ліполітика Тріада pb serum в зону ПІДБОРІДДЯ", categoryId: "cat-27", durationMin: 60, price: 4800 },
  { id: "svc-210", name: "Ін'єкція ліполітика Тріада pb serum в зону ЩОК", categoryId: "cat-27", durationMin: 60, price: 4800 },
  { id: "svc-211", name: "Ін'єкція ліполітика Тріада pb serum в зону ЖИВОТА", categoryId: "cat-27", durationMin: 60, price: 4800 },
  { id: "svc-212", name: "Ін'єкція ліполітика Тріада pb serum в зону над КОЛІНАМИ", categoryId: "cat-27", durationMin: 60, price: 4800 },
  { id: "svc-213", name: "Ін'єкція ліполітика Тріада pb serum в зону ПЛЕЧА", categoryId: "cat-27", durationMin: 60, price: 4800 },
  { id: "svc-214", name: "Контагіозний молюск", categoryId: "cat-29", durationMin: 60, price: 500 },
  { id: "svc-215", name: "Контагіозний молюск (інтимна зона)", categoryId: "cat-29", durationMin: 60, price: 700 },
  { id: "svc-216", name: "Контагіозний молюск (до 10шт)", categoryId: "cat-29", durationMin: 60, price: 450 },
  { id: "svc-217", name: "Контагіозний молюск (від 11, кожен наступний)", categoryId: "cat-29", durationMin: 60, price: 400 },
  { id: "svc-218", name: "Папіломи (до 10шт)", categoryId: "cat-29", durationMin: 60, price: 200 },
  { id: "svc-219", name: "Папіломи (від 11, кожна наступна)", categoryId: "cat-29", durationMin: 60, price: 150 },
  { id: "svc-220", name: "Доброякісне новоутворення шкіри (до 3мм)", categoryId: "cat-29", durationMin: 60, price: 500 },
  { id: "svc-221", name: "Доброякісне новоутворення шкіри (до 5мм)", categoryId: "cat-29", durationMin: 60, price: 1000 },
  { id: "svc-222", name: "Доброякісне новоутворення шкіри (до 10мм)", categoryId: "cat-29", durationMin: 60, price: 1500 },
  { id: "svc-223", name: "Бородавка (до 3мм)", categoryId: "cat-29", durationMin: 60, price: 500 },
  { id: "svc-224", name: "Бородавка (до 5мм)", categoryId: "cat-29", durationMin: 60, price: 1000 },
  { id: "svc-225", name: "Гістологія новоутворення", categoryId: "cat-29", durationMin: 60, price: 1000 },
  { id: "svc-226", name: "Видалення міліума 1шт", categoryId: "cat-29", durationMin: 60, price: 100 },
];

/** Service duration (min) by id. */
export function catalogDurationMin(serviceId: string): number | undefined {
  return CATALOG_SERVICES.find((s) => s.id === serviceId)?.durationMin;
}
